name: Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Stable
      run: rustup toolchain install stable --profile=default

    - name: Run clippy
      run: cargo clippy --all -- -D warnings
