name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ocaml-compiler: ["4.14.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use OCaml ${{ matrix.ocaml-compiler }}
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - name: Install deps
      run: curl https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz | tar xJ

    - name: Set Opam env
      run: opam env | tr '\n' ' ' >> $GITHUB_ENV

    - name: Add Opam switch to PATH
      run: opam var bin >> $GITHUB_PATH

    - run: opam install dune ctypes-foreign

    - name: Rust example
      run: PATH="$PATH:$PWD/futhark-nightly-linux-x86_64/bin" opam exec -- make test

  macos:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        ocaml-compiler: ["4.14.0"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use OCaml ${{ matrix.ocaml-compiler }}
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - name: Install deps
      run: brew update && brew install futhark

    - name: Run tests
      run: cd examples/rust && cargo test --verbose --all

    - name: Set Opam env
      run: opam env | tr '\n' ' ' >> $GITHUB_ENV

    - name: Add Opam switch to PATH
      run: opam var bin >> $GITHUB_PATH

    - run: opam install dune ctypes-foreign

    - name: OCaml exmaple
      run: opam exec -- make test
